### ISSUE TITLE
Newer Electron version?

### ISSUE THREAD

**Issue by takase1121** [flathub/xyz.armcord.ArmCord#20]
Currently, armcord flatpak uses electron 21. There are some bugfixes from Electron > 22 that would be useful for Wayland (tray bar crashing armcord). Why isn't the newer version used?

**Comment by orowith2os** [comment]
Screensharing, mainly. Until newer Electron versions support screensharing without issues, I won't be updating this to a newer Electron.

**Comment by takase1121** [comment]
> Screensharing, mainly. Until newer Electron versions support screensharing without issues, I won't be updating this to a newer Electron.

At the same time, only newer Electron versions support screen sharing on GNOME Wayland via legacy capturer. Electron is really a mixed bag right now. I'll just wait until the work on Chromium on Wayland to stabilize.

**Comment by orowith2os** [comment]
> only newer Electron versions support screen sharing on GNOME Wayland via legacy capturer. 

I'm using what's currently in this repo (21) just fine with the legacy capturer. It's the newer versions (>21) that break screensharing.
