### ISSUE TITLE
Installed package is 3.2.0 update wants to install 3.1.4

### ISSUE THREAD

**Issue by ranomier** [flathub/xyz.armcord.ArmCord#22]
I don't know if this an upstream flatpak issue or an issue with this package, but this doesn't seem right:

![image](https://github.com/flathub/xyz.armcord.ArmCord/assets/7649949/1eab7538-c03f-4017-b361-0eee4d7c46a4)

Did i misunderstand something?

**Comment by amsyarzero** [comment]
Can confirm that this just happened to me too in Discover.
![image](https://github.com/flathub/xyz.armcord.ArmCord/assets/81513934/6d96234f-5f36-4164-ad40-665b8f7fa818)

**Comment by orowith2os** [comment]
I want to say this is an issue with Flatpak itself, because the metadata says it's on 3.2.0. The binaries I'm grabbing confirm this. 

I also searched locally and both Beta and Stable provide 3.2.0. Could this be an issue with your system configurations? What version does ArmCord say it has when you actually update it?

![image](https://github.com/flathub/xyz.armcord.ArmCord/assets/93224879/f8565cf1-f1cf-4919-bce3-2f9764b15539)

**Comment by ranomier** [comment]
I use discord a lot. So i don't want to update. How would i roll back?

EDIT: When i do the search it shows me this:
![image](https://github.com/flathub/xyz.armcord.ArmCord/assets/7649949/bd394169-a459-4dfe-98a7-3e75f15d5055)

EDIT2: About the system configuration. I have archlinux updated to the latest packages and flatpak installed from the normal repos.

EDIT3:
![image](https://github.com/flathub/xyz.armcord.ArmCord/assets/7649949/260e4872-d6ad-4469-8157-09d2e203b814)
mmh i have flathub as user and system, i will try to remove the user one

That didn't do the trick

**Comment by orowith2os** [comment]
>  How would i roll back?

The Flatpak documentation mentions this: https://docs.flatpak.org/en/latest/tips-and-tricks.html#downgrading

**Comment by ranomier** [comment]
```
⋊> ~ flatpak info xyz.armcord.ArmCord                                                                                                                                                                        

ArmCord - ArmCord is a custom client designed to enhance your Discord
experience while keeping everything lightweight.

          ID: xyz.armcord.ArmCord
         Ref: app/xyz.armcord.ArmCord/x86_64/stable
        Arch: x86_64
      Branch: stable
     Version: 3.2.0
     License: OSL-3.0
      Origin: flathub
  Collection: org.flathub.Stable
Installation: system
   Installed: 232,1 MB
     Runtime: org.freedesktop.Platform/x86_64/22.08
         Sdk: org.freedesktop.Sdk/x86_64/22.08

      Commit: 97e76575c4086e4fcd0534afbc255b5c539303f07adb7d00ccade45c31a2740e
      Parent: 7e5471b590ca2bb98924c97b798d058615e91bf3c29d0dd5834468113626e404
     Subject: Update 2 modules (#16) (79094076)
        Date: 2023-05-14 15:58:01 +0000
```
Above is my local info, you see the commit begins with 97e
Below you see that there is a new update beginning with ff0

So there is a remote update and looking at your repo you seemed to have made updates to the package itself, weird.
```
⋊> ~ flatpak remote-info --log flathub xyz.armcord.ArmCord                                                                                                                                                   00:13:06
        ID: xyz.armcord.ArmCord
       Ref: app/xyz.armcord.ArmCord/x86_64/stable
      Arch: x86_64
    Branch: stable
Collection: org.flathub.Stable
  Download: 91,7 MB
 Installed: 232,5 MB
   Runtime: org.freedesktop.Platform/x86_64/22.08
       Sdk: org.freedesktop.Sdk/x86_64/22.08

    Commit: ff0d0f89466ba167c7e09507164a1d87560071c5e42bf95ef3bc33290c974a95
    Parent: 97e76575c4086e4fcd0534afbc255b5c539303f07adb7d00ccade45c31a2740e
   Subject: Better wayland detecting (#14) (26684e80)
      Date: 2023-06-11 01:35:38 +0000
   History:

    Commit: 97e76575c4086e4fcd0534afbc255b5c539303f07adb7d00ccade45c31a2740e
   Subject: Update 2 modules (#16) (79094076)
      Date: 2023-05-14 15:58:01 +0000

    Commit: 7e5471b590ca2bb98924c97b798d058615e91bf3c29d0dd5834468113626e404
   Subject: Create flathub.json (#13) (8444e08a)
      Date: 2023-04-10 18:40:33 +0000

    Commit: a046be4a0fa9172ad5493972c82f3cb1e9e393f06e3a8e0a75c91ac73c5e7550
   Subject: Tray icons (#10) (5841ac5d)
      Date: 2023-04-02 08:12:40 +0000

    Commit: 7512a7ea795bbc0e94a74a5963f1230043dd7806d17b4c6de2e6f06d16fa85d0
   Subject: Make README easier to understand (#9) (353ce9a9)
      Date: 2023-03-31 02:43:44 +0000

    Commit: 31071bc622ecac79bceae0c78552cf172f810ef3a12d1d384999b319b41a44a3
   Subject: (don't) fix the tray icon not showing (#8) (8b111504)
      Date: 2023-03-25 05:06:41 +0000

    Commit: bddc8b01f0e2c2afb608504fca22baaa95729b97feadabc2144ea6b641d6c655
   Subject: (don't) fix the tray icon not showing (#8) (8b111504)
      Date: 2023-03-25 05:06:41 +0000

    Commit: ccefa8ef8f1ed4ca10b4a2ac45b8dbc30c27fa2ab1ddb7bad0434a9bfc4e548a
   Subject: Update xyz.armcord.ArmCord.metainfo.xml (b2dfe1dd)
      Date: 2023-03-20 01:27:51 +0000

    Commit: f8ff9bb2b9d4a9b689c3e69fbc28d5c545d88ba52d9b8446f2afa34a5ae6b731
   Subject: Update 2 modules (e87db781)
      Date: 2023-03-15 01:19:04 +0000

    Commit: cc7bc1ab576ec5be6553de1e7f28f79c405d643c5f3e4e7415b274f64a768417
   Subject: Update README.md (d36e546b)
      Date: 2023-03-13 14:00:55 +0000

    Commit: b99b670019bb522d811dd5d77bad8f098ceb581d45c42ff026698f1810bf170a
   Subject: Use arm64 binaries, not arm (fb0fe0b8)
      Date: 2023-03-13 07:25:52 +0000
```
EDIT: I'm updating now, it takes very long ...

**Comment by ranomier** [comment]
So this is so weird.
![image](https://github.com/flathub/xyz.armcord.ArmCord/assets/7649949/9b18f7d0-eee7-4772-bc44-7fa37f92909f)

remote version is old, but the updated local one is new.

and armcord itself also reports 3.2.0

**Comment by orowith2os** [comment]
Maybe it's a cache issue? Dig around ~/.local/share/flatpak and /var/lib/flatpak for any cache files and remove those.

**Comment by ranomier** [comment]
Aren't the cache files more in .cache?
But i moved those and nothing changed.

And the data in .local/share/flatpak seems importand

**Comment by orowith2os** [comment]
Can you reproduce this again now?

**Comment by orowith2os** [comment]
I'm going to assume this is fixed. Notify me if it still shows up.
