### ISSUE TITLE
USE_WAYLAND=1 doesnt work anymore

### ISSUE THREAD

**Issue by Apacelus** [flathub/xyz.armcord.ArmCord#23]
After the latest update the app starts in Xwayland again. Here is the log:
```
$ USE_WAYLAND=1 flatpak run xyz.armcord.ArmCord 
Using Wayland, enabling PipeWire for video capture.
Screenshare may be broken on first start.
Make sure you have the legacy screencapturer enabled.
Wayland socket not available, running through Xwayland.
Using NVIDIA on Wayland, applying workaround
Passing the following arguments to Electron: --enable-gpu-rasterization --enable-zero-copy --enable-gpu-compositing --enable-native-gpu-memory-buffers --enable-oop-rasterization --disable-gpu-blocklist --disable-gpu-sandbox --enable-features=UseSkiaRenderer,WebRTCPipeWireCapturer,WebRTCPipeWireCapturer
```

**Comment by Apacelus** [comment]
I just had a look at the latest commit. Seems like the issue is that socket=wayland is not enabled by default. Manually enabling it via flatseal fixes the issue and armcord starts in wayland (even without USE_WAYLAND=1)

**Comment by Apacelus** [comment]
Native titlebar doesnt work anymore though. When the ArmCord theme is set to `Native` the app doesnt have a titlebar at all

**Comment by orowith2os** [comment]
I can't solve that last issue, that's probably unrelated to my packaging. And yes, I intentionally stopped using USE_WAYLAND=1, this implementation is much cleaner.

**Comment by Apacelus** [comment]
> Seems like the issue is that socket=wayland is not enabled by default. Manually enabling it via flatseal fixes the issue and armcord starts in wayland (even without USE_WAYLAND=1)

That can be fixed

**Comment by orowith2os** [comment]
I have no plans to enable Wayland by default.

**Comment by Apacelus** [comment]
Why not?

**Comment by orowith2os** [comment]
Wayland is still known to be buggy with Electron, and I've encountered quite a few showstoppers, like broken fractional scaling. Once everything works, I'll enable it by default. Otherwise, it's a very simple change for the user to make.

**Comment by Aegeontis** [comment]
> it's a very simple change for the user to make.

If the user knows what to do...
Wayland may be buggy, but so is Xwayland (in my experience much more buggy than wayland). And at least wayland runs "natively".
