### ISSUE TITLE
A bunch of issues

### ISSUE THREAD

**Issue by ghost** [flathub/xyz.armcord.ArmCord#3]
- instead of checking for `USE_WAYLAND` 1 or not 1, check for `USE_WAYLAND=0` then do an else to run in wayland automatically, otherwise in regular wayland sessions without this env set armcord will just run in Xwayland (like, this is a little stupid)

  (I am in a gnome wayland session)
  ![image](https://user-images.githubusercontent.com/76652465/226094756-fe7595d3-da11-4af2-9842-a93cabf83770.png)
  ![image](https://user-images.githubusercontent.com/76652465/226094773-c7184e59-989d-453e-b71b-01773318c0ee.png)
- bunch of errors like → `[3:0318/092418.526397:ERROR:bus.cc(399)] Failed to connect to the bus: Failed to connect to socket /run/dbus/system_bus_socket: No such file or directory` (not sure if this can be fixed)
- `Passthrough is not supported, GL is egl, ANGLE is`... ← another error
- `Gtk: gtk_widget_get_scale_factor: assertion 'GTK_IS_WIDGET (widget)' failed` spam when resizing window
- armcord remains as small as the splash window in wayland
  ![image](https://user-images.githubusercontent.com/76652465/226094732-40fc1593-ee8a-48f4-b5d1-83e07c35f9a4.png)
- armcord still segfaults after trying to screenshare, `WebRTCPipeWireCapturer` is still no good I guess?
  
    securityOrigin: 'https://discord.com/',
  userGesture: true,
  videoRequested: true,
  audioRequested: true
}
[0318/093525.032068:ERROR:scoped_ptrace_attach.cc(27)] ptrace: Operation not permitted (1)
/app/bin/startarmcord: line 31:     3 Segmentation fault      zypak-wrapper /app/bin/armcord/armcord "${FLAGS[@]}" "$@"

nit: `UseOzonePlatform` is not required since electron 12

**Comment by orowith2os** [comment]
Many of these issues are mainly upstream ones, afaik. The only one I'm responsible for is not setting USE_WAYLAND=1, which you can do by setting the `--env=USE_WAYLAND=1` in the manifest; I'll gladly merge that in. I'm going to continue to keep the check for 1.

I'm not sure why it complains about dbus permissions, but find the talk names needed and I'll add those.

Everything else should go to upstream.

**Comment by Apacelus** [comment]
Not sure exactly how its supposed to work, but there is a permission called fallback-x11 in flatseal, which implies that apps can try to run in Wayland mode by default and fallback to x11 if they cant find wayland. Perhaps you could somehow use that option?
This would also allow unsetting the normal x11 flag, which would likely remove the "Unsafe: Uses a legacy windowing system" warning in software stores

**Comment by ghost** [comment]
@orowith2os sorry, cba
@Apacelus I'm not even sure what you're talking about

**Comment by orowith2os** [comment]
@Apacelus I could do that, will update in a bit.

**Comment by orowith2os** [comment]
@unlwly Flatpak has Wayland, X11, and fallback-x11 permissions. The first two are self explanatory, fallback-x11 paired with Wayland allows opening up the X11 socket when not using Wayland or Wayland isn't available.

I don't have any interest in changing the current checks, at least not until many of the issues with Wayland and Electron are cleared up. If someone wants to force Wayland, all the tooling is there.



Overall, I'd say many of these issues belong upstream, and not here. Closing until any notable flatpak-specific issues are found.
