### ISSUE TITLE
Wayland doesn't use correct cursor theme

### ISSUE THREAD

**Issue by jamiethecat** [flathub/xyz.armcord.ArmCord#36]
When running the Flatpak with Wayland, it uses some weird small cursor. With XWayland, it uses the Adwaita cursor like normal.

**Comment by orowith2os** [comment]
This should be filed with upstream Chromium; they use a vendored libwayland, and as such, don't get the OOTB stuff that the FreeDesktop runtime sets up for everything to Just Work. A workaround would be to set `XCURSOR_PATH=/run/host/user-share/icons:/run/host/share/icons` (and is more or less what the fd.o libwayland sets).

**Comment by Aegeontis** [comment]
Why not just set that in https://github.com/flathub/xyz.armcord.ArmCord/blob/master/xyz.armcord.ArmCord.yml

[THe Signal desktop app does that](https://github.com/flathub/org.signal.Signal/blob/master/org.signal.Signal.yaml#L42)

**Comment by jamiethecat** [comment]
> Why not just set that in https://github.com/flathub/xyz.armcord.ArmCord/blob/master/xyz.armcord.ArmCord.yml
> 
> [THe Signal desktop app does that](https://github.com/flathub/org.signal.Signal/blob/master/org.signal.Signal.yaml#L42)

The official Discord Flatpak too, I guess that's a good idea till it's fixed upstream.
