### ISSUE TITLE
Full screen on wayland looks weird

### ISSUE THREAD

**Issue by Apacelus** [flathub/xyz.armcord.ArmCord#4]
This does **NOT** happen with the appimage version.
Here is a screenshot demonstrating the issue:
![image](https://user-images.githubusercontent.com/46828271/226144644-fc012ac6-4700-4626-b0f2-b569062c5d30.png)
The green is my background, not the app

OS: Fedora
DE: Gnome 43.3 on Wayland

**Comment by orowith2os** [comment]
Does it happen with the AppImage version running in the same environment?

Download the AppImage and enter the Downloads directory. Run `flatpak run --filesystem=~/Downloads --command=bash xyz.armcord.ArmCord` and `./ArmCord.AppImage`. 

If the issue is with ArmCord, it'll happen here too. If not, something's wrong with my packaging.

You also now see why I use X11 by default here.

**Comment by Apacelus** [comment]
When I try that, I get: `fusermount: mount failed: Operation not permitted` and `bash: sudo: command not found` when I try with sudo

**Comment by orowith2os** [comment]
Make sure you own the file, and there isn't any sudo inside of the sandbox anyways. Does the issue happen on native Wayland, or Xwayland?

**Comment by orowith2os** [comment]
Are you also on NVIDIA or AMD?

**Comment by Apacelus** [comment]
> Make sure you own the file, and there isn't any sudo inside of the sandbox anyways.

I own the file.

>  Does the issue happen on native Wayland, or Xwayland?

I forced the app to run under native wayland

> Are you also on NVIDIA or AMD?

Nvidia, rtx 3070. Havent had wayland issues for a while now

**Comment by orowith2os** [comment]
I'm tempted to chalk it up to a NVIDIA issue. They still don't have the best Wayland support, along with Electron maybe still having a few quirks. Reproduce on an AMD/Intel system if you can.

**Comment by Apacelus** [comment]
@orowith2os yeah I suppose this might be an nvidia issue. I dont suppose there is a way to package the needed lib into the flatpak like the appimage does?

**Comment by orowith2os** [comment]
That depends on what the needed lib is. We also just repackage the AppImage directly, so whatever that uses should also be used here.

**Comment by Saladin1812** [comment]
For me clicking screenshare simply crashes the client without any logs.. any way to get logs at runtime ?

**Comment by Apacelus** [comment]
> For me clicking screenshare simply crashes the client without any logs.. any way to get logs at runtime ?

1. Not relevant to this issue
2. Happens in appimage builds too

**Comment by orowith2os** [comment]
I can't reproduce this issue *at all* on my end, and since we use everything from the AppImage, I don't really see where the issue is.... Plus, if there's a NVIDIA lib needed, it should be bundled in the NVIDIA driver, not here.

**Comment by Apacelus** [comment]
@orowith2os well now im getting the same issue on my pure intel laptop

**Comment by orowith2os** [comment]
@Apacelus I'm going to need specifics on how to reproduce this issue.

**Comment by Apacelus** [comment]
1. Install app
2. Maximize app

Im on Fedora 37, with gnome and popos theme (I highly doubt the theme is causing it, as it works with the appimage and never happened to any other app)

**Comment by orowith2os** [comment]
Disable any GNOME modifications you might have and try to reproduce.

**Comment by Apacelus** [comment]
Hmm, seems to be indeed an issue with the popos theme, because it doesnt happen when I switch back to adwaita.

**Comment by orowith2os** [comment]
Then not really my issue, it should be taken up with the theme devs.
