### ISSUE TITLE
Current 3.2.4 version is broken, please update to the latest release

### ISSUE THREAD

**Issue by juni-purr** [flathub/xyz.armcord.ArmCord#42]
https://github.com/ArmCord/ArmCord/releases/tag/v3.2.4-e27

**Comment by orowith2os** [comment]
That is a prerelease, and is only to be used if you're affected by https://github.com/ArmCord/ArmCord/issues/454. If you want to use that, you can easily modify this Flatpak to pull those binaries yourself, and let others use those. 

I want to try and closely follow the upstream repository (and stable releases) from now on.
